### PR TITLE
Support redirecting stderr to stdout

### LINKED ISSUE #113: Consider supporting redirecting stderr to stdout
## Problem
Babashka/process currently easily supports controlling destinations for stderr and stdout.

But... it does not currently easily support merging stderr and stdout to a single output stream.
This can be very useful when you don't care about stderr vs stdout but do care about capturing all output in the order it occurs over time.

## JDK Support
[`ProcessBuilder` includes `redirectErrorStream`](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html#redirectErrorStream--).
Docs on its effect are found in the [`ProcessBuilder` class JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html).

## Explore Current Behaviour
Using the current release 0.4.16 of babashka/process, and a wee bb `outerr.clj` script to explore:
```Clojure
(println "I am written to stdout")

(binding [*out* *err*]
  (println "I am written to stderr"))
```

Today we can easily get stderr and stdout separately:
```Clojure
(require '[babashka.process :as p])

(-> (p/shell {:out :string :err :string} "bb outerr.clj")
    (select-keys [:out :err]))
;; => {:out "I am written to stdout\n", :err "I am written to stderr\n"}
```

But merging stderr to stdout, while possible, is a bit lower level than it could be:
```Clojure
(let [pb (p/pb {:out :string} "bb outerr.clj")
      pb-obj (:pb pb)]
  (.redirectErrorStream pb-obj true)
  (:out @(p/start pb)))
;; => "I am written to stdout\nI am written to stderr\n"
```

## Proposed API change
@borkdude and I hashed out syntax on Slack and he came up with the succinct `:err :out`.
Nice!

With this new syntax, the lower-level example above could be re-expressed like so:
```Clojure
(-> (p/shell {:out :string :err :out} "bb outerr.clj")
    :out)
;; => "I am written to stdout\nI am written to stderr\n"
```

The `:err :out` syntax will be applicable to all API fns where `:err` is accepted in `opts`. 

## Next Steps
After @borkdude eyeballs the above, I'll proceed with a PR for review that includes both code and doc updates.

### PR DESCRIPTION
**Pull request by lread**
New tests launch clojure to as part of testing capturing stderr. Adjusted CI to download clojure deps before running tests so we did not pollute stderr with clojure's `Downloading: org/clojure...` stderr messages.

Bumped GitHub action setup-clojure. Prior to bump installed clojure was not launching in GitHub Actions default Windows shell.

Closes #113

### CODE REVIEW

**Comment by lread** [comment]
Heya @borkdude:

1. Please review examples in README. 
2. Also lemme know what you think about having to download deps before tests are run. If you are ok with this, perhaps this should be abstracted with a bb task? 
3. I happened to notice is that not many tests are run on Windows. 
Is this intentional? Something we want to address? (separately, of course)

As always, happy to collab and make changes.

**Comment by borkdude** [comment]
1. No problem
2. Seems fine. We could also shell out to `bb -cp ""` which does not need to download any deps, perhaps? And it would be a tad faster than spinning up a new JVM for a unit test
3. I found porting the existing examples to Windows a bit tedious, so I only ran cases where I knew that Windows behavior differs

**Comment by lread** [comment]
2. Ah, I think the `-cp` idea is a good one. This way when contributors run tests locally they won't suffer confusing false-failures if they haven't downloaded deps. I'll make a wee commit after I've had enough coffee.
3. I am willing to try to get the test suite running under Windows. But this is a gift you might not want as it might be a maintenance burden to keep them all running on Windows moving forward - but I could help with that. I was thinking that rather than using OS-specific commands to use a small clojure or bb script that could emit/exit whatever/however the specific test needs. Lemme know if an issue is of interest here. Also very much understand if you don't want it.

**Comment by borkdude** [comment]
@lread I'd be open to 3 but maybe as a separate issue/PR and it's not that high priority, but your help is welcome and appreciated.

**Pull request merged**
