### PR TITLE
Add shutdown hook to destroy the process

### PR DESCRIPTION
**Pull request by Heliosmaster**
This PR adds a shutdown hook which automatically destroys the spawned process when the caller is about to quit.

Example usage: We have a babashka script which starts a bunch of (running processes). When we Ctrl-C to quit the script, we would like the processes to terminate as well.

We added an option to pass to `process` to disable this behavior.

### CODE REVIEW

**Comment by borkdude** [comment]
@Heliosmaster Seems good to me. I prefer the name without question mark (use question marks for predicate functions only: https://github.com/bbatsov/clojure-style-guide/issues/182#issuecomment-516969043). 

Proposed name: `:destroy-on-shutdown` which defaults to `true`.

**Comment by Heliosmaster** [comment]
@borkdude sounds good. In our previous implementation it was opt-in with `destroy-on-shutdown?` as the option flag :-)  We'll remove the question mark and force push.

**Comment by borkdude** [comment]
@Heliosmaster Documentation would also be nice.

**Comment by borkdude** [comment]
@Heliosmaster @hamann I have an example bb script here to kill all children of a process:

https://github.com/borkdude/babashka/blob/master/test/babashka/scripts/kill_child_processes.bb

Maybe it would also be useful in this context. Not sure if it warrants a different option.

**Comment by hamann** [comment]
@borkdude After playing with the proposed solution for several times we realized that just calling `(.destroy proc)` is not sufficient in our case because it immediately returns and let the main process exit, but the subprocess is still alive for a while, produceses uncontrollable output on the terminal and then exits. So in our case we would also have to add `(.waitFor proc)` and maybe `(.destroyForcibly proc)` after some time as a last resort.
So I have the feeling that instead of implementing the shutdown logic in the process function we should give the caller control over the shutdown behaviour for example with a nasty callback function or passing an atom where the process object will be stored/referenced.

**Comment by borkdude** [comment]
OK, I'll wait with merging until we have more clarity on this.

**Pull request closed without merging**
